/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: ['class'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['IBM Plex Mono', 'Roboto Mono', 'monospace'],
      },
      colors: {
        brand: {
          DEFAULT: 'var(--brand)',
          weak: 'var(--brand-weak)',
          50: 'var(--brand-50)',
          100: 'var(--brand-100)',
          200: 'var(--brand-200)',
          300: 'var(--brand-300)',
          400: 'var(--brand-400)',
          500: 'var(--brand-500)',
          600: 'var(--brand-600)',
          700: 'var(--brand-700)',
          800: 'var(--brand-800)',
          900: 'var(--brand-900)',
          950: 'var(--brand-950)',
        },
        positive: {
          DEFAULT: 'var(--accent-pos)',
          50: 'var(--accent-pos-50)',
          100: 'var(--accent-pos-100)',
          200: 'var(--accent-pos-200)',
          300: 'var(--accent-pos-300)',
          400: 'var(--accent-pos-400)',
          500: 'var(--accent-pos-500)',
          600: 'var(--accent-pos-600)',
          700: 'var(--accent-pos-700)',
          800: 'var(--accent-pos-800)',
          900: 'var(--accent-pos-900)',
          950: 'var(--accent-pos-950)',
        },
        negative: {
          DEFAULT: 'var(--accent-neg)',
          50: 'var(--accent-neg-50)',
          100: 'var(--accent-neg-100)',
          200: 'var(--accent-neg-200)',
          300: 'var(--accent-neg-300)',
          400: 'var(--accent-neg-400)',
          500: 'var(--accent-neg-500)',
          600: 'var(--accent-neg-600)',
          700: 'var(--accent-neg-700)',
          800: 'var(--accent-neg-800)',
          900: 'var(--accent-neg-900)',
          950: 'var(--accent-neg-950)',
        },
        background: 'var(--bg)',
        foreground: 'var(--text-primary)',
        card: {
          DEFAULT: 'var(--card)',
          foreground: 'var(--text-primary)',
        },
        surface: {
          DEFAULT: 'var(--surface)',
          hover: 'var(--surface-hover)',
        },
        muted: {
          DEFAULT: 'var(--text-muted)',
          foreground: 'var(--text-tertiary)',
        },
        border: 'var(--border)',
        input: 'var(--border)',
        ring: 'var(--accent-pos)',
        primary: {
          DEFAULT: 'var(--brand)',
          foreground: 'var(--text-primary)',
        },
        secondary: {
          DEFAULT: 'var(--text-secondary)',
          foreground: 'var(--text-primary)',
        },
        destructive: {
          DEFAULT: 'var(--error)',
          foreground: 'var(--text-primary)',
        },
        success: {
          DEFAULT: 'var(--success)',
          foreground: 'var(--text-primary)',
        },
        warning: {
          DEFAULT: 'var(--warning)',
          foreground: 'var(--text-primary)',
        },
      },
      spacing: {
        '1': 'var(--space-1)',
        '2': 'var(--space-2)',
        '3': 'var(--space-3)',
        '4': 'var(--space-4)',
        '5': 'var(--space-5)',
        '6': 'var(--space-6)',
        '8': 'var(--space-8)',
        '10': 'var(--space-10)',
        '12': 'var(--space-12)',
        '16': 'var(--space-16)',
        '20': 'var(--space-20)',
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'var(--radius-sm)',
        sm: 'calc(var(--radius-sm) - 2px)',
      },
      boxShadow: {
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
      },
      animation: {
        'fade-in': 'fadeIn 0.5s var(--ease-out)',
        'slide-up': 'slideUp 0.3s var(--ease-out)',
        'marquee': 'marquee 25s linear infinite',
        'pulse-glow': 'pulse-glow 2s ease-in-out infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        marquee: {
          '0%': { transform: 'translateX(0%)' },
          '100%': { transform: 'translateX(-100%)' },
        },
        'pulse-glow': {
          '0%, 100%': { boxShadow: '0 0 5px var(--accent-pos)' },
          '50%': { boxShadow: '0 0 20px var(--accent-pos)' },
        },
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/typography'),
  ],
}