[phases.setup]
nixPkgs = ['nodejs', 'pnpm']

[phases.install]
cmd = 'pnpm install --frozen-lockfile'

[phases.build]
cmd = 'pnpm --filter @propsage/core build && pnpm --filter @propsage/api build'

[start]
cmd = 'cd apps/api && PORT=${PORT:-8080} node dist/index.js'
